Description: CDK RDS Postgres Stack
Resources:
  RdsDbSecretSecrets6F036D51:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CDK RDS Postgres Admin Secret
      GenerateSecretString:
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        GenerateStringKey: password
        PasswordLength: 16
        SecretStringTemplate: '{"username":"dcpsadmin"}'
      Name: db/development/password
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/DbSecret/Secrets/Resource
  RdsParameterGroupC6FE513C:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: CloudFormation AWS RDS PostgreSQL Database Parameter Group
      Family: postgres11
      Parameters:
        shared_preload_libraries: auto_explain,pg_stat_statements,pg_hint_plan,pgaudit
        log_statement: ddl
        log_connections: "1"
        log_disconnections: "1"
        log_lock_waits: "1"
        log_min_duration_statement: "5000"
        auto_explain.log_min_duration: "5000"
        auto_explain.log_verbose: "1"
        log_rotation_age: "1440"
        log_rotation_size: "102400"
        rds.log_retention_period: "10080"
        random_page_cost: "1"
        track_activity_query_size: "16384"
        idle_in_transaction_session_timeout: "7200000"
        statement_timeout: "7200000"
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/ParameterGroup/ParameterGroup/Resource
  RdsRdsInstanceSubnetGroup988E36CE:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RdsInstance database
      SubnetIds:
        - subnet-0963f01ebd2a61ee5
        - subnet-00f9dbdb1bdb95141
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: Name
          Value: Master Database
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/RdsInstance/SubnetGroup
  RdsRdsInstanceSecurityGroup62093104:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RdsInstance database
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: Name
          Value: Master Database
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
      VpcId: vpc-02646997cb1a175ea
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/RdsInstance/SecurityGroup/Resource
  RdsRdsInstanceSecurityGroupfrom00000IndirectPortEEA8736B:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      Description: from 0.0.0.0/0:{IndirectPort}
      FromPort:
        Fn::GetAtt:
          - RdsRdsInstance295A7CFA
          - Endpoint.Port
      GroupId:
        Fn::GetAtt:
          - RdsRdsInstanceSecurityGroup62093104
          - GroupId
      ToPort:
        Fn::GetAtt:
          - RdsRdsInstance295A7CFA
          - Endpoint.Port
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/RdsInstance/SecurityGroup/from 0.0.0.0_0:{IndirectPort}
  RdsRdsInstance295A7CFA:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: "20"
      AutoMinorVersionUpgrade: false
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      DBInstanceIdentifier: cdk-rds-postgres
      DBName: demo
      DBParameterGroupName:
        Ref: RdsParameterGroupC6FE513C
      DBSubnetGroupName:
        Ref: RdsRdsInstanceSubnetGroup988E36CE
      DeleteAutomatedBackups: true
      DeletionProtection: false
      Engine: postgres
      EngineVersion: "11.7"
      MasterUsername:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: RdsDbSecretSecrets6F036D51
            - :SecretString:username::}}
      MasterUserPassword:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: RdsDbSecretSecrets6F036D51
            - :SecretString:password::}}
      MaxAllocatedStorage: 30
      MultiAZ: false
      PreferredBackupWindow: 19:00-20:30
      PreferredMaintenanceWindow: Sun:22:00-Sun:22:30
      PubliclyAccessible: true
      StorageEncrypted: false
      StorageType: gp2
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: Name
          Value: Master Database
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
      VPCSecurityGroups:
        - Fn::GetAtt:
            - RdsRdsInstanceSecurityGroup62093104
            - GroupId
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/RdsInstance/Resource
  SnsCloudWatchSnsTopicDE611FF3:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: cdk-rds-postgres-sns
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/SnsCloudWatch/SnsTopic/Resource
  SnsCloudWatchSnsTopicjohnmacisgmailcom58B9C46D:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn:
        Ref: SnsCloudWatchSnsTopicDE611FF3
      Endpoint: johnmacis@gmail.com
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/SnsCloudWatch/SnsTopic/johnmacis@gmail.com/Resource
  SnsCloudWatchCpuAlarm7BA02418:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      AlarmActions:
        - Ref: SnsCloudWatchSnsTopicDE611FF3
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Ref: RdsRdsInstance295A7CFA
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Period: 300
      Statistic: Average
      Threshold: 75
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/SnsCloudWatch/CpuAlarm/Resource
  SnsCloudWatchIopsAlarm6666191D:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      AlarmActions:
        - Ref: SnsCloudWatchSnsTopicDE611FF3
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Ref: RdsRdsInstance295A7CFA
      MetricName: WriteIOPS
      Namespace: AWS/RDS
      Period: 60
      Statistic: Maximum
      Threshold: 7000
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/SnsCloudWatch/IopsAlarm/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.54.0,@aws-cdk/assets=1.54.0,@aws-cdk/aws-cloudwatch=1.54.0,@aws-cdk/aws-cloudwatch-actions=1.54.0,@aws-cdk/aws-codeguruprofiler=1.54.0,@aws-cdk/aws-ec2=1.54.0,@aws-cdk/aws-events=1.54.0,@aws-cdk/aws-iam=1.54.0,@aws-cdk/aws-kms=1.54.0,@aws-cdk/aws-lambda=1.54.0,@aws-cdk/aws-logs=1.54.0,@aws-cdk/aws-rds=1.54.0,@aws-cdk/aws-s3=1.54.0,@aws-cdk/aws-s3-assets=1.54.0,@aws-cdk/aws-sam=1.54.0,@aws-cdk/aws-secretsmanager=1.54.0,@aws-cdk/aws-sns=1.54.0,@aws-cdk/aws-sns-subscriptions=1.54.0,@aws-cdk/aws-sqs=1.54.0,@aws-cdk/aws-ssm=1.54.0,@aws-cdk/cloud-assembly-schema=1.54.0,@aws-cdk/core=1.54.0,@aws-cdk/cx-api=1.54.0,@aws-cdk/region-info=1.54.0,jsii-runtime=node.js/v12.13.1
Outputs:
  RdsDbInstanceEndPoint40B46390:
    Description: CDK RDS Endpoint Address
    Value:
      Fn::GetAtt:
        - RdsRdsInstance295A7CFA
        - Endpoint.Address
    Export:
      Name: DbInstanceEndPoint
  SnsCloudWatchSnsTopicOutput6618745A:
    Description: CDK SNS Topic
    Value:
      Fn::Join:
        - ""
        - - https://console.aws.amazon.com/sns/home?region=us-east-1#/topic/
          - Ref: SnsCloudWatchSnsTopicDE611FF3
