Description: CDK RDS Postgres Stack
Resources:
  RdsDbSecretSecrets6F036D51:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CDK RDS Postgres Admin Secret
      GenerateSecretString:
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        GenerateStringKey: password
        PasswordLength: 16
        SecretStringTemplate: '{"username":"dcpsadmin"}'
      Name: db/development/password
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/DbSecret/Secrets/Resource
  RdsDbSecretSecretsAttachedSecret211AAC9A:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: RdsDbSecretSecrets6F036D51
      TargetId:
        Ref: RdsRdsInstance295A7CFA
      TargetType: AWS::RDS::DBInstance
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/DbSecret/Secrets/AttachedSecret/Resource
  RdsDbSecretSecretsRotateSecrets9DB95B4A:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId:
        Ref: RdsDbSecretSecrets6F036D51
      RotationLambdaARN: arn:aws:lambda:us-east-1:009963118558:function:MyLambdaRotationFunction
      RotationRules:
        AutomaticallyAfterDays: 30
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/DbSecret/Secrets/RotateSecrets/Resource
  RdsParameterGroupC6FE513C:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: CloudFormation AWS RDS PostgreSQL Database Parameter Group
      Family: postgres11
      Parameters:
        shared_preload_libraries: auto_explain,pg_stat_statements,pg_hint_plan,pgaudit
        log_statement: ddl
        log_connections: "1"
        log_disconnections: "1"
        log_lock_waits: "1"
        log_min_duration_statement: "5000"
        auto_explain.log_min_duration: "5000"
        auto_explain.log_verbose: "1"
        log_rotation_age: "1440"
        log_rotation_size: "102400"
        rds.log_retention_period: "10080"
        random_page_cost: "1"
        track_activity_query_size: "16384"
        idle_in_transaction_session_timeout: "7200000"
        statement_timeout: "7200000"
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/ParameterGroup/ParameterGroup/Resource
  ? RdsRdsInstanceSGfromCdkRdsPostgresStackRdsEc2BastionInstanceSG1A923F645432EF44AEAA
  : Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from ec2 bastion to rds
      FromPort: 5432
      GroupId: sg-0029660ed9d7f2b93
      SourceSecurityGroupId: sg-021b67bf18034de08
      ToPort: 5432
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/RdsInstanceSG/from CdkRdsPostgresStackRdsEc2BastionInstanceSG1A923F64:5432
  RdsRdsInstanceSGfromCdkRdsPostgresStackRdsSecretsLambdaSGDE4E1E415432552DA0AF:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from secrets lambda function to rds
      FromPort: 5432
      GroupId: sg-0029660ed9d7f2b93
      SourceSecurityGroupId: sg-0d7e30b362b15ded6
      ToPort: 5432
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/RdsInstanceSG/from CdkRdsPostgresStackRdsSecretsLambdaSGDE4E1E41:5432
  RdsRdsInstanceSubnetGroup988E36CE:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RdsInstance database
      SubnetIds:
        - subnet-00fa9604ac4e8dda5
        - subnet-0c3e3b4b580683721
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: Name
          Value: Master Database
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/RdsInstance/SubnetGroup
  RdsRdsInstance295A7CFA:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      AutoMinorVersionUpgrade: false
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      DBInstanceIdentifier: cdk-rds-postgres
      DBName: demo
      DBParameterGroupName:
        Ref: RdsParameterGroupC6FE513C
      DBSubnetGroupName:
        Ref: RdsRdsInstanceSubnetGroup988E36CE
      DeleteAutomatedBackups: true
      DeletionProtection: false
      Engine: postgres
      EngineVersion: "11.7"
      MasterUsername:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: RdsDbSecretSecrets6F036D51
            - :SecretString:username::}}
      MasterUserPassword:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: RdsDbSecretSecrets6F036D51
            - :SecretString:password::}}
      MaxAllocatedStorage: 30
      MultiAZ: false
      PreferredBackupWindow: 19:00-20:30
      PreferredMaintenanceWindow: Sun:22:00-Sun:22:30
      PubliclyAccessible: false
      StorageEncrypted: true
      StorageType: gp2
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: Name
          Value: Master Database
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
      VPCSecurityGroups:
        - sg-0029660ed9d7f2b93
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/RdsInstance/Resource
  ? RdsReadReplicaReadReplicaSGfromCdkRdsPostgresStackRdsReadReplicaRdsInstanceSecurityGroup255F9D6F543200C07A86
  : Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from master rds to read replica
      FromPort: 5432
      GroupId: sg-06c7aba440aa0e94d
      SourceSecurityGroupId: sg-0029660ed9d7f2b93
      ToPort: 5432
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/ReadReplica/ReadReplicaSG/from CdkRdsPostgresStackRdsReadReplicaRdsInstanceSecurityGroup255F9D6F:5432
  ? RdsReadReplicaReadReplicaSGfromCdkRdsPostgresStackRdsReadReplicaEc2BastionInstanceSGC4647EEC5432895B17D6
  : Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from ec2 bastion to read replica
      FromPort: 5432
      GroupId: sg-06c7aba440aa0e94d
      SourceSecurityGroupId: sg-021b67bf18034de08
      ToPort: 5432
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/ReadReplica/ReadReplicaSG/from CdkRdsPostgresStackRdsReadReplicaEc2BastionInstanceSGC4647EEC:5432
  RdsReadReplicaSubnetGroupE96BA67D:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for ReadReplica database
      SubnetIds:
        - subnet-00fa9604ac4e8dda5
        - subnet-0c3e3b4b580683721
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: Name
          Value: Read Replica Database
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/ReadReplica/ReadReplica/SubnetGroup
  RdsReadReplica3BCA60CE:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      CopyTagsToSnapshot: true
      DBInstanceIdentifier: cdk-rds-postgres-read
      DBSubnetGroupName:
        Ref: RdsReadReplicaSubnetGroupE96BA67D
      DeleteAutomatedBackups: true
      DeletionProtection: false
      PubliclyAccessible: false
      SourceDBInstanceIdentifier:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":rds:us-east-1:009963118558:db:"
            - Ref: RdsRdsInstance295A7CFA
      StorageType: gp2
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: Name
          Value: Read Replica Database
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
      VPCSecurityGroups:
        - sg-06c7aba440aa0e94d
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Rds/ReadReplica/ReadReplica/Resource
  SnsCloudWatchSnsTopicDE611FF3:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: cdk-rds-postgres-sns
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/SnsCloudWatch/SnsTopic/Resource
  SnsCloudWatchSnsTopicjohnmacisgmailcom58B9C46D:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn:
        Ref: SnsCloudWatchSnsTopicDE611FF3
      Endpoint: johnmacis@gmail.com
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/SnsCloudWatch/SnsTopic/johnmacis@gmail.com/Resource
  SnsCloudWatchCpuAlarm7BA02418:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      AlarmActions:
        - Ref: SnsCloudWatchSnsTopicDE611FF3
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Ref: RdsRdsInstance295A7CFA
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Period: 300
      Statistic: Average
      Threshold: 75
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/SnsCloudWatch/CpuAlarm/Resource
  SnsCloudWatchIopsAlarm6666191D:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      AlarmActions:
        - Ref: SnsCloudWatchSnsTopicDE611FF3
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Ref: RdsRdsInstance295A7CFA
      MetricName: WriteIOPS
      Namespace: AWS/RDS
      Period: 60
      Statistic: Maximum
      Threshold: 7000
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/SnsCloudWatch/IopsAlarm/Resource
  Ec2InstanceEc2BastionInstanceSGfrom00000229DD2EA83:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      Description: from 0.0.0.0/0:22
      FromPort: 22
      GroupId: sg-021b67bf18034de08
      ToPort: 22
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Ec2Instance/Ec2BastionInstanceSG/from 0.0.0.0_0:22
  Ec2InstanceEc2InstanceRoleE0DD0E54:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: Name
          Value: CdkRdsPostgresStack/Ec2Instance/Ec2
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Ec2Instance/Ec2/InstanceRole/Resource
  Ec2InstanceEc2InstanceProfile0C0DA720:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: Ec2InstanceEc2InstanceRoleE0DD0E54
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Ec2Instance/Ec2/InstanceProfile
  Ec2InstanceEc205A8953C:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      IamInstanceProfile:
        Ref: Ec2InstanceEc2InstanceProfile0C0DA720
      ImageId:
        Ref: SsmParameterValueawsserviceamiamazonlinuxlatestamznamihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: t2.micro
      KeyName: jmacis-keypair
      SecurityGroupIds:
        - sg-021b67bf18034de08
      SubnetId: subnet-078960f7b5a4dcf41
      Tags:
        - Key: AppName
          Value: test-rds-postgres-db
        - Key: CostCenter
          Value: "1000"
        - Key: Env
          Value: Development
        - Key: Name
          Value: CdkRdsPostgresStack/Ec2Instance/Ec2
        - Key: StackName
          Value: CDK-RDS-POSTGRES-DB
        - Key: StackOwner
          Value: John Macis
      UserData:
        Fn::Base64: >-
          #!/bin/bash

          sudo yum update -y

          wget https://yum.postgresql.org/11/redhat/rhel-6.9-x86_64/postgresql11-libs-11.8-1PGDG.rhel6.x86_64.rpm

          wget https://yum.postgresql.org/11/redhat/rhel-6.9-x86_64/postgresql11-11.8-1PGDG.rhel6.x86_64.rpm

          sudo yum clean all

          sudo rpm -ivh postgresql11-libs-11.8-1PGDG.rhel6.x86_64.rpm

          sudo rpm -ivh postgresql11-11.8-1PGDG.rhel6.x86_64.rpm

          psql --version
    DependsOn:
      - Ec2InstanceEc2InstanceRoleE0DD0E54
    Metadata:
      aws:cdk:path: CdkRdsPostgresStack/Ec2Instance/Ec2/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.54.0,@aws-cdk/assets=1.54.0,@aws-cdk/aws-cloudwatch=1.54.0,@aws-cdk/aws-cloudwatch-actions=1.54.0,@aws-cdk/aws-codeguruprofiler=1.54.0,@aws-cdk/aws-ec2=1.54.0,@aws-cdk/aws-events=1.54.0,@aws-cdk/aws-iam=1.54.0,@aws-cdk/aws-kms=1.54.0,@aws-cdk/aws-lambda=1.54.0,@aws-cdk/aws-logs=1.54.0,@aws-cdk/aws-rds=1.54.0,@aws-cdk/aws-s3=1.54.0,@aws-cdk/aws-s3-assets=1.54.0,@aws-cdk/aws-sam=1.54.0,@aws-cdk/aws-secretsmanager=1.54.0,@aws-cdk/aws-sns=1.54.0,@aws-cdk/aws-sns-subscriptions=1.54.0,@aws-cdk/aws-sqs=1.54.0,@aws-cdk/aws-ssm=1.54.0,@aws-cdk/cloud-assembly-schema=1.54.0,@aws-cdk/core=1.54.0,@aws-cdk/cx-api=1.54.0,@aws-cdk/region-info=1.54.0,jsii-runtime=node.js/v12.13.1
Outputs:
  RdsDbSecretSecretsManagerArnB7243E37:
    Description: CDK RDS Secrets Manager Arn
    Value:
      Ref: RdsDbSecretSecrets6F036D51
  RdsDbInstanceEndPoint40B46390:
    Description: CDK RDS Endpoint Address
    Value:
      Fn::GetAtt:
        - RdsRdsInstance295A7CFA
        - Endpoint.Address
    Export:
      Name: DbInstanceEndPoint
  RdsDbInstanceIdentifier9455219A:
    Description: CDK RDS Instance Identifier
    Value:
      Fn::Join:
        - ""
        - - https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=
          - Ref: RdsRdsInstance295A7CFA
          - ;is-cluster=false
  RdsReadReplicaReadReplicaEndPointDF856F29:
    Description: CDK Read Replica Endpoint Address
    Value:
      Fn::GetAtt:
        - RdsReadReplica3BCA60CE
        - Endpoint.Address
    Export:
      Name: ReadReplicaEndPoint
  SnsCloudWatchSnsTopicOutput6618745A:
    Description: CDK SNS Topic
    Value:
      Fn::Join:
        - ""
        - - https://console.aws.amazon.com/sns/home?region=us-east-1#/topic/
          - Ref: SnsCloudWatchSnsTopicDE611FF3
  Ec2InstanceBastionIdentifier94C7A843:
    Description: CDK EC2 Instance Identifier
    Value:
      Fn::Join:
        - ""
        - - https://console.aws.amazon.com/ec2/home?region=
          - Ref: AWS::Region
          - "#Instances:search="
          - Ref: Ec2InstanceEc205A8953C
          - ;sort=instanceId
Parameters:
  ? SsmParameterValueawsserviceamiamazonlinuxlatestamznamihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter
  : Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn-ami-hv
