AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  endpoint:
    Type: String
    Description: The Secrets Manager endpoint to hit
  functionName:
    Type: String
    Description: The name of the lambda function
  invokingServicePrincipal:
    Type: String
    Description: The Service Principal of the invoking service
    Default: secretsmanager.amazonaws.com
  vpcSubnetIds:
    Type: CommaDelimitedList
    Description: List of VPC subnet IDs
    Default: ""
  vpcSecurityGroupIds:
    Type: CommaDelimitedList
    Description: List of VPC security grouop IDs
    Default: ""
  kmsKeyArn:
    Type: String
    Description: The kms key used to encrypt the secret being rotated
    Default: ""
Conditions:
  AddVpcConfig:
    Fn::And:
      - Fn::Not:
          - Fn::Equals:
              - ""
              - Fn::Join:
                  - ""
                  - Ref: vpcSubnetIds
      - Fn::Not:
          - Fn::Equals:
              - ""
              - Fn::Join:
                  - ""
                  - Ref: vpcSecurityGroupIds
  KmsKeyArnExists:
    Fn::Not:
      - Fn::Equals:
          - ""
          - Ref: kmsKeyArn
Resources:
  SecretsManagerRDSPostgreSQLRotationSingleUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Ref: functionName
      Description: Conducts an AWS SecretsManager secret rotation for RDS PostgreSQL using single user rotation scheme
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri:
        Bucket: awsserverlessrepo-changesets-plntc6bfnfj
        Key: 009963118558/arn:aws:serverlessrepo:us-east-1:297356227824:applications-SecretsManagerRDSPostgreSQLRotationSingleUser-versions-1.1.58/35d184f5-4ac0-4ad4-b0cf-9ddc79855a61
      Timeout: 30
      Policies:
        - VPCAccessPolicy: {}
        - AWSSecretsManagerRotationPolicy:
            FunctionName:
              Ref: functionName
        - Fn::If:
            - KmsKeyArnExists
            - Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - kms:Decrypt
                    - kms:DescribeKey
                    - kms:GenerateDataKey
                  Resource:
                    Ref: kmsKeyArn
            - Ref: AWS::NoValue
      Environment:
        Variables:
          SECRETS_MANAGER_ENDPOINT:
            Ref: endpoint
      VpcConfig:
        Fn::If:
          - AddVpcConfig
          - SubnetIds:
              Ref: vpcSubnetIds
            SecurityGroupIds:
              Ref: vpcSecurityGroupIds
          - Ref: AWS::NoValue
      Tags:
        SecretsManagerLambda: Rotation
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - SecretsManagerRDSPostgreSQLRotationSingleUser
          - Arn
      Principal:
        Ref: invokingServicePrincipal
Outputs:
  RotationLambdaARN:
    Description: The ARN of the rotation lambda
    Value:
      Fn::GetAtt:
        - SecretsManagerRDSPostgreSQLRotationSingleUser
        - Arn
